# Copyright (c) 2025, NVIDIA CORPORATION.  All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "csp-health-monitor.fullname" . }}
  labels:
    {{- include "csp-health-monitor.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "csp-health-monitor.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with ((.Values.global).podAnnotations | default .Values.podAnnotations) }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "csp-health-monitor.selectorLabels" . | nindent 8 }}
    spec:
      {{- with ((.Values.global).imagePullSecrets | default .Values.imagePullSecrets) }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "csp-health-monitor.fullname" . }}
      volumes:
      - name: config-volume
        configMap:
          name: {{ include "csp-health-monitor.fullname" . }}
          items:
          - key: config.toml
            path: config.toml
      - name: mongo-app-client-cert
        secret:
          secretName: mongo-app-client-cert-secret # Defined in mongodb-store chart
          optional: true
      - name: platform-connector-uds
        hostPath:
          path: /var/run/nvsentinel
          type: DirectoryOrCreate
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default ((.Values.global).image).tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
          - "--config=/etc/config/config.toml"
          - "--metrics-port={{ ((.Values.global).metricsPort) | default 2112 }}"
          - "--mongo-client-cert-mount-path=/etc/ssl/mongo-client"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          ports:
            - name: metrics
              containerPort: {{ ((.Values.global).metricsPort) | default 2112 }}
              protocol: TCP
          volumeMounts:
          - name: config-volume
            mountPath: /etc/config/
          - name: mongo-app-client-cert
            mountPath: /etc/ssl/mongo-client
            readOnly: true
          env:
            - name: LOG_LEVEL
              value: "{{ .Values.logLevel }}"
          envFrom:
            - configMapRef:
                name: mongodb-config
                optional: true

        - name: maintenance-notifier
          image: "{{ .Values.quarantineTriggerEngine.image.repository }}:{{ .Values.image.tag | default ((.Values.global).image).tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.quarantineTriggerEngine.image.pullPolicy | default .Values.image.pullPolicy }}
          securityContext:
            runAsUser: 0
          args:
          - "--config=/etc/config/config.toml"
          - "--mongo-client-cert-mount-path=/etc/ssl/mongo-client"
          - "--uds-path=/run/nvsentinel/nvsentinel.sock"
          - "--metrics-port=2113"
          resources:
            {{- toYaml .Values.quarantineTriggerEngine.resources | default .Values.resources | nindent 12 }}
          ports:
            - name: metrics-sidecar
              containerPort: 2113
              protocol: TCP
          volumeMounts:
          - name: config-volume
            mountPath: /etc/config/
          - name: mongo-app-client-cert
            mountPath: /etc/ssl/mongo-client
            readOnly: true
          - name: platform-connector-uds
            mountPath: /run/nvsentinel
          env:
            - name: LOG_LEVEL
              value: "{{ .Values.quarantineTriggerEngine.logLevel | default .Values.logLevel }}"
          envFrom:
            - configMapRef:
                name: mongodb-config
                optional: true
      restartPolicy: Always
      {{- with (((.Values.global).systemNodeSelector) | default .Values.nodeSelector) }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with (((.Values.global).affinity) | default .Values.affinity) }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with (((.Values.global).systemNodeTolerations) | default .Values.tolerations) }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
