# Copyright (c) 2025, NVIDIA CORPORATION.  All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

{{- if or (eq .Values.global.clusterType "standalone") (eq .Values.global.clusterType "mgmt") }}
{{- if and .Values.global.datastore (eq .Values.global.datastore.provider "postgresql") }}
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: postgresql-ca-issuer
  namespace: {{ .Release.Namespace }}
spec:
  ca:
    secretName: postgresql-root-ca-secret
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: selfsigned-ca-issuer
  namespace: {{ .Release.Namespace }}
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: postgresql-root-ca
  namespace: {{ .Release.Namespace }}
spec:
  isCA: true
  commonName: postgresql-root-ca
  secretName: postgresql-root-ca-secret
  duration: 87600h   # 10 years
  renewBefore: 720h  # 30 days before expiration
  privateKey:
    algorithm: RSA
    size: 4096
  issuerRef:
    name: selfsigned-ca-issuer
    kind: Issuer
---
# PostgreSQL Server Certificate
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: postgresql-server-cert
  namespace: {{ .Release.Namespace }}
spec:
  secretName: postgresql-server-cert
  duration: 8760h   # 1 year
  renewBefore: 360h # 15 days before expiration
  commonName: postgresql
  dnsNames:
    - postgresql
    - {{ printf "%s-postgresql.%s.svc.cluster.local" .Release.Name .Release.Namespace }}
    - {{ printf "%s-postgresql.%s.svc" .Release.Name .Release.Namespace }}
    - {{ printf "postgresql.%s.svc.cluster.local" .Release.Namespace }}
    - {{ printf "postgresql.%s.svc" .Release.Namespace }}
  issuerRef:
    name: postgresql-ca-issuer
    kind: Issuer
---
# PostgreSQL Client Certificate
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: postgresql-client-cert
  namespace: {{ .Release.Namespace }}
spec:
  secretName: postgresql-client-cert
  duration: 8760h   # 1 year
  renewBefore: 360h # 15 days before expiration
  commonName: postgresql
  issuerRef:
    name: postgresql-ca-issuer
    kind: Issuer
{{- end }}
{{- end }}
