# Copyright (c) 2025, NVIDIA CORPORATION.  All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: v2
name: nvsentinel
description: Helm chart for NVSentinel
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: gpu-health-monitor
    version: "0.1.0"
    condition: global.gpuHealthMonitor.enabled
  - name: mongodb-store
    version: "0.1.0"
    condition: global.mongodbStore.enabled
  - name: postgresql
    version: "15.5.38"
    condition: postgresql.enabled
  - name: fault-quarantine
    version: "0.1.0"
    condition: global.faultQuarantine.enabled
  - name: node-drainer
    version: "0.1.0"
    condition: global.nodeDrainer.enabled
  - name: fault-remediation
    version: "0.1.0"
    condition: global.faultRemediation.enabled
  - name: health-events-analyzer
    version: "0.1.0"
    condition: global.healthEventsAnalyzer.enabled
  - name: csp-health-monitor
    version: "0.1.0"
    condition: global.cspHealthMonitor.enabled
  - name: syslog-health-monitor
    version: "0.1.0"
    condition: global.syslogHealthMonitor.enabled
  - name: incluster-file-server
    version: "0.1.0"
    condition: global.inclusterFileServer.enabled
  - name: labeler
    version: "0.1.0"
    condition: global.labeler.enabled
  - name: janitor
    version: "0.1.0"
    condition: global.janitor.enabled
  - name: metadata-collector
    version: "0.1.0"
    condition: global.metadataCollector.enabled
  - name: kubernetes-object-monitor
    version: "0.1.0"
    condition: global.kubernetesObjectMonitor.enabled
  - name: event-exporter
    version: "0.1.0"
    condition: global.eventExporter.enabled
